# See:
#   https://pre-commit.com
#   https://pre-commit.com/hooks.html
#   https://learn.scientific-python.org/development/guides/style/
# uv run pre-commit install
# uv run pre-commit autoupdate
# uv run pre-commit run --all-files

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: end-of-file-fixer
      exclude: ^\.typings/
    - id: trailing-whitespace
      exclude: ^\.typings/
    - id: check-merge-conflict
    - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      # Run the linter (first).
      - id: ruff-check
        types_or: [python, pyi]
        exclude: ^\.typings/
      # Run the formatter (second).
      - id: ruff-format
        types_or: [python, pyi]
        exclude: ^\.typings/

  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.37.3
    hooks:
      - id: basedpyright
        exclude: ^\.typings/

  - repo: https://github.com/astral-sh/uv-pre-commit
    # https://docs.astral.sh/uv/guides/integration/pre-commit/
    rev: 0.9.28
    hooks:
      - id: uv-lock
        name: uv lock
        files: 'pyproject.toml'
